### PR TITLE
Increase max length of Comment.page field from 30 to 32 characters.

### PR DESCRIPTION
**Pull request by R2th**
# Description

_Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context._

_Please remove options that are not relevant_
Type of change: bug fix, new feature, refactor, or something else?

## What

What does the PR do?

## Why

Why this PR is needed?

Fixes # (issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have explained the purpose of this PR.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the README/documentation
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Informed of breaking changes, testing and migrations (if applicable).
- [ ] Attached screenshots (if applicable).

By submitting this pull request, I confirm that my contribution is made under the terms of the AGPL-3.0 License.

### CODE REVIEW

**Review by leduythuccs — APPROVED** [review]
LGTM

**Comment by hieplpvip** [comment]
Why only 32? Increasing 30 to 32 only adds 2 characters

**Comment by R2th** [comment]
@hieplpvip because the limit page was 30 while the contest code is 32
so requests like this will fail
Image 1582x542

**Comment by hieplpvip** [comment]
Ok, I can say for sure that 32 is not enough. The reason is that the contest key is prepended with `c:` to form the associated page (see `get_comment_page`). I've checked all `get_comment_page` definitions. 34 is good.

Please also increase the limit for `CommentLock`.

**Pull request merged**
