### PR TITLE
Migrate unique slug org

### PR DESCRIPTION
**Pull request by trantuyet**
# Description

_Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context._

_Please remove options that are not relevant_
Type of change: bug fix, new feature, refactor, or something else?

## What

What does the PR do?
Update slug column in organization to unique

## Why

Why this PR is needed?

Fixes # (issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have explained the purpose of this PR.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the README/documentation
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Informed of breaking changes, testing and migrations (if applicable).
- [ ] Attached screenshots (if applicable).

By submitting this pull request, I confirm that my contribution is made under the terms of the AGPL-3.0 License.

### CODE REVIEW

**Comment by hieplpvip** [comment]
Migration looks good, but you need to add `unique=True` to `slug` field in model:
https://github.com/VNOI-Admin/OJ/blob/a860684d172d276e082784a4f391824b5c7b18bd/judge/models/profile.py#L42-L43

Lint is failing so please fix that too. Thanks.

**Comment by trantuyet** [comment]
.

**Comment by trantuyet** [comment]
.

**Comment by trantuyet** [comment]
I am opening a new one

**Pull request closed without merging**
