### PR TITLE
Add batchadduser

### PR DESCRIPTION
**Pull request by hieplpvip**
Sample input csv:

```csv
username,fullname
hieplpvip,"Le Bao Hiep"
```

### CODE REVIEW

**Comment by leduythuccs** [comment]
Does this script ignore the header?

**Comment by hieplpvip** [comment]
`DictReader` is used so yes

**Comment by leduythuccs** [comment]
The logic seems fine, i will test it tmr

**Review by leduythuccs — APPROVED** [review]
LGTM

**Pull request merged**
